import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col items-center`}>
        <header className="h-14 w-full max-w-4xl py-2 items-center flex justify-evenly">
          <Link className="active:text-green-600" href={"/ssr"}>
            SSR
          </Link>
          <Link className="active:text-green-600" href={"/ssr-stream"}>
            ssr-streaming
          </Link>
          <Link className="active:text-green-600" href={"/ssg"}>
            SSG
          </Link>
          <Link className="active:text-green-600" href={"/isr"}>
            ISR
          </Link>
          
        </header>
        {children}
        </body>
    </html>
  );
}
